Додавання Dockerfile та README.md
Hutiir-Craft-Food/FoodBackend pull request #12
Opened 2024-07-02 20:06 UTC by YP0n

Зверни увагу на те, що я змінив application.yml, а саме додав 
properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
у файл pom.xml додав залежності 
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.cdimascio</groupId>
            <artifactId>java-dotenv</artifactId>
            <version>5.2.2</version>
        </dependency>
Ще створив, для колег, файл Readme.md, щоб краще орієнтуватися в задумці та реалізації фіч проєкту.

2024-07-02 20:21 UTC, Vladik-gif commented on Dockerfile
> +COPY .env .env
Ця стрічка не потрібна так як файл .env докер не бачить, файл .env лиге для розробника локально

2024-07-02 20:21 UTC, Vladik-gif commented on README.md
> +# Marketplace Backend(Khutir Craftu)
Ця інформація поки що зайва так як все одно при бажанні можна зробити завантажити на docker hub

2024-07-02 20:21 UTC, Vladik-gif commented on pom.xml
> +            <groupId>io.github.cdimascio</groupId>
Що це за залежність, і яка користь від неї?

2024-07-02 20:23 UTC, Vladik-gif reviewed
Юра, займайся будь ласка dockerfile. Ти знову чіпаєш ті класи після якого прийдеться тобі або Каті виправляти

2024-07-02 20:28 UTC, YP0n commented on pom.xml
> +            <groupId>io.github.cdimascio</groupId>
<dependency>
            <groupId>io.github.cdimascio</groupId>
            <artifactId>java-dotenv</artifactId>
            <version>5.2.2</version>
        </dependency>
бібліотека для завантаження та використання файлу .env

2024-07-02 20:29 UTC, YP0n commented
Влад, я у цьому коміті класів взагалі не чіпав.

2024-07-03 11:51 UTC, YP0n commented on README.md
> +# Marketplace Backend(Khutir Craftu)
Це ж для Нас, щоб було зрозуміло.

2024-07-03 11:53 UTC, YP0n commented on Dockerfile
> +COPY .env .env
Видалив. Взагалі то середа розробки видавала помилку про ненаходження файлу .env, аж до поки я не став його передавати у тілі запуску контейнера, про, що, до речі, вказав у Редмі файлі )

2024-07-03 19:36 UTC, Vladik-gif commented on src/main/java/com/gmail/ypon2003/marketplacebackend/services/ProductService.java
> +            Person person = personRepository.findById(productDTO.personId())
Цілий метод він не правильно написаний,

2024-07-03 20:02 UTC, YP0n commented on src/main/java/com/gmail/ypon2003/marketplacebackend/services/ProductService.java
> +            Person person = personRepository.findById(productDTO.personId())
Можливо і не правильно і я б хотів це обговорити, тому, що метод працює.

2024-07-03 20:03 UTC, YP0n commented on Dockerfile
Запускав. Працює.

2024-07-03 20:04 UTC, YP0n commented on src/main/java/com/gmail/ypon2003/marketplacebackend/services/ProductService.java
Шо це?

2024-07-04 05:49 UTC, Vladik-gif commented on src/main/java/com/gmail/ypon2003/marketplacebackend/services/ProductService.java
> +            Person person = personRepository.findById(productDTO.personId())
Воно то може і працює, але ти використовуєш DTO не так як я розповідав вам, ще навіщо ти вішаєш Optional на метод getId() і навіщо ти дату перевіряєш на null, якщо і як зрозуміло що там її немає, ти просто повинен був написати LocalDateTime.now()

2024-07-04 07:59 UTC, Vladik-gif requested changes
Виправляй!

2024-07-04 07:59 UTC, Vladik-gif commented on src/main/java/com/gmail/ypon2003/marketplacebackend/MarketPlaceBackendApplication.java
> +        dotenv.entries().forEach(entry -> System.setProperty(entry.getKey(), entry.getValue()));
Це також нам не потрібно,

2024-07-04 14:13 UTC, YP0n commented on src/main/java/com/gmail/ypon2003/marketplacebackend/MarketPlaceBackendApplication.java
> +        dotenv.entries().forEach(entry -> System.setProperty(entry.getKey(), entry.getValue()));
Видаляю.

2024-07-04 17:13 UTC, Vladik-gif commented on src/main/java/com/gmail/ypon2003/marketplacebackend/services/ProductService.java
> +            Person person = personRepository.findById(productDTO.personId())
Та не треба виправляти, Катя сама виправить)

2024-07-04 19:18 UTC, YP0n commented
До завдання які зауваження?

2024-07-04 19:41 UTC, Vladik-gif requested changes
Виправляй! І давай наступного разу будемо разом вирішувати яку залежність добавляти)

2024-07-04 19:41 UTC, Vladik-gif commented on src/main/java/com/gmail/ypon2003/marketplacebackend/MarketPlaceBackendApplication.java
> -        dotenv.entries().forEach(entry -> System.setProperty(entry.getKey(), entry.getValue()));
Ти забув ще видалити саму залежність!

2024-07-04 19:41 UTC, Vladik-gif commented on pom.xml
> +            <artifactId>java-dotenv</artifactId>
Тепер же треба видалити залежність, вона також не потрібна!

2024-07-14 19:12 UTC, merged